name: sharethechurch
description: A new Flutter project.

publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cloud_firestore: null
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: null
  firebase_core: null
  firebase_core_platform_interface: 4.4.0
  firebase_storage: ^10.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_native_splash: ^2.2.3+1
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  fluttertoast: ^8.0.9
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  location: ^4.4.0
  mailjet: ^1.0.3+3
  path_provider: ^2.0.11
  rename: ^2.0.1
  sendgrid_mailer: ^0.1.3
  shared_preferences: ^2.0.15
  syncfusion_flutter_pdfviewer: ^20.2.44-beta
  url_launcher: ^6.1.5
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/
